//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordManager.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public System.DateTime ReminderDate { get; set; }
        public string Message { get; set; }
        public string Channel { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
